#version 460 core

struct InstanceData{
    vec3 instance_size;
    uint _pad1;
    vec3 instance_position_offset;
    uint _pad2;
};

struct VoxelData{
    uint four_voxels;
};

struct Vertex{
    float x, y, z;
};

struct DrawElementsIndirectCommand{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (binding = 0, std430) readonly restrict buffer ssbo { VoxelData voxels[]; };
layout (binding = 1, std430) writeonly restrict buffer final_vertices { Vertex vertices[]; };
layout (binding = 2, std430) writeonly restrict buffer final_indices { uint indices[];};
layout (binding = 3, std430) writeonly restrict buffer final_packed {uint packedData[]; };
layout (binding = 4, std430) restrict buffer indirect_buffer { DrawElementsIndirectCommand indirect_command; };
layout (binding = 5, std140) uniform instance_data_buffer { InstanceData instance_data; };

uint get_voxel(uint x, uint y, uint z, vec3 size) {
    uint idx = x + (y * uint(size.x)) + (z * uint(size.x) * uint(size.y));
    return (voxels[idx >> 2].four_voxels >> (8 * (idx & 3))) & 255;
}

void create_face(vec3 start, vec3 end, uint col, uint normal_idx) {
    float face_length = end.y - start.y; 
    
    uint base_idx = atomicAdd(indirect_command.count, 6);
    
    uint face_idx = base_idx / 6;
    uint base_vtx = (base_idx / 6) * 4;

    uint packed_val = (col & 255) | (normal_idx << 8);
    packedData[face_idx] = packed_val;

    float z_offset = (normal_idx == 3) ? 1.0 : 0.0;
    vec3 base = start + vec3(0.0, 0.0, z_offset);
    
    vec3 pos0 = base;                                    // c0
    vec3 pos1 = base + vec3(1.0, 0.0, 0.0);              // c1
    vec3 pos2 = base + vec3(1.0, 1.0 + face_length, 0.0);// c2
    vec3 pos3 = base + vec3(0.0, 1.0 + face_length, 0.0);// c3

    vertices[base_vtx + 0] = Vertex(pos0.x, pos0.y, pos0.z);
    vertices[base_vtx + 1] = Vertex(pos1.x, pos1.y, pos1.z);
    vertices[base_vtx + 2] = Vertex(pos2.x, pos2.y, pos2.z);
    vertices[base_vtx + 3] = Vertex(pos3.x, pos3.y, pos3.z);

    if (normal_idx == 3) { 
        indices[base_idx + 0] = base_vtx + 0;
        indices[base_idx + 1] = base_vtx + 3;
        indices[base_idx + 2] = base_vtx + 2;
        indices[base_idx + 3] = base_vtx + 0;
        indices[base_idx + 4] = base_vtx + 2;
        indices[base_idx + 5] = base_vtx + 1;
    } else { 
        indices[base_idx + 0] = base_vtx + 0;
        indices[base_idx + 1] = base_vtx + 1;
        indices[base_idx + 2] = base_vtx + 2;
        indices[base_idx + 3] = base_vtx + 0;
        indices[base_idx + 4] = base_vtx + 2;
        indices[base_idx + 5] = base_vtx + 3;
    }
}

void main() {
    uint ix = gl_GlobalInvocationID.x;
    uint iy = gl_GlobalInvocationID.y;
    vec3 size = instance_data.instance_size.xyz;

    if (ix >= size.x || iy >= size.y) return;

    vec3 offset_size = size;
    vec3 strip_base_pos = vec3(iy, 0, ix); 
    strip_base_pos += instance_data.instance_position_offset.yzx - 
         vec3(floor(offset_size.y / 2.0), floor(offset_size.z / 2.0), floor(offset_size.x / 2.0));

    uint prev_col_neg = 0; vec3 start_neg = vec3(-1); 
    uint prev_col_pos = 0; vec3 start_pos = vec3(-1); 
    
    uint size_z = uint(size.z);

    // Sweep along Input Z
    for (uint iz = 0; iz < size_z; iz++) {
        uint curr = get_voxel(ix, iy, iz, size);
        
        uint col_neg = 0;
        uint col_pos = 0;
        
        if (curr != 0) {
            uint n_neg = (ix > 0) ? get_voxel(ix - 1, iy, iz, size) : 0;
            uint n_pos = (ix < size.x - 1) ? get_voxel(ix + 1, iy, iz, size) : 0;

            if (n_neg == 0) col_neg = curr;
            if (n_pos == 0) col_pos = curr;
        }

        vec3 current_pos = strip_base_pos + vec3(0, iz, 0);

        // --- Face -Z ---
        if (col_neg != prev_col_neg) {
            if (prev_col_neg != 0) create_face(start_neg, current_pos - vec3(0,1,0), prev_col_neg, 2);
            if (col_neg != 0) start_neg = current_pos;
        }
        prev_col_neg = col_neg;

        // --- Face +Z ---
        if (col_pos != prev_col_pos) {
            if (prev_col_pos != 0) create_face(start_pos, current_pos - vec3(0,1,0), prev_col_pos, 3);
            if (col_pos != 0) start_pos = current_pos;
        }
        prev_col_pos = col_pos;
    }

    vec3 end_pos = strip_base_pos + vec3(0, size_z - 1, 0);
    if (prev_col_neg != 0) create_face(start_neg, end_pos, prev_col_neg, 2);
    if (prev_col_pos != 0) create_face(start_pos, end_pos, prev_col_pos, 3);
}